name: 'Add body to release'
branding:
  icon: 'tag'
  color: 'purple'
description: 'Add a body from a file to a GitHub release'
inputs:
  token:
    description: Personal access token (PAT) used to create releases
    required: true
  path:
    description: Relative path to the file name
    required: true
runs:
  using: 'node12'
  main: 'distribution/index.js'
